Refresh yarn.lock in preparation for 3.1 (#10516)
* Restrict version of linting packages

When refreshing the yarn.lock files, with ^ semver ranges on linters, it upgraded the lint packages to newer versions that had different linting decisions (causing lots of formatting changes). I think upgrading lint to new linting decisions should be a very explicit decision (not just refreshing yarn, but actually updating required versions), since lots of formatting changes can be effected.

* Restrict storybook version

* Refresh yarn.lock

This was done by deleting the lock file and installing fresh.

* Fix linting error.

This fixes one place where a promise was not handled.

* Turn off strict null checking for typedoc.

Strict null checking is giving some errors when compiling the docs. For example https://github.com/vega/vega-lite/pull/7352 and another one:

Error: buildutils/src/local-repository.ts:113:34 - error TS2345: Argument of type '{ prev_npm: string; prev_yarn: string; pid: number | undefined; }' is not assignable to parameter of type 'JSONObject'.
  Property 'pid' is incompatible with index signature.
    Type 'number | undefined' is not assignable to type 'JSONValue'.
      Type 'undefined' is not assignable to type 'JSONValue'.

113   utils.writeJSONFile(info_file, data);
                                     ~~~~

Error: node_modules/vega-lite/build/src/vega.schema.d.ts:34:19 - error TS2344: Type 'null' does not satisfy the constraint 'SignalRef | ExprRef'.

34     value?: Value<null>;
                     ~~~~

* Update reference UI screenshots to reflect a single launcher tab not having a close “X”.

In the latest 3.0 release, if a single launcher tab is open, it does not have a close X in the tab (since we must have at least one tab open). In master, the close X does appear, but does nothing when clicking on it. After  #10516, the 3.0 behavior is restored: if a single launcher tab is open, it does not have an X.