Fix too vague locator which was failing if settings were not yet filtered
```
Error: locator.click: Error: strict mode violation: locator('.form-group:has-text("Show Filter Bar by Default")').locator('label') resolved to 14 elements:
    1) <label>…</label> aka locator('label').filter({ hasText: 'Navigate to current folder' })
    2) <label>…</label> aka locator('label').filter({ hasText: 'Filter on file name with a' })
    ...
```

because it takes time for `query` to kick in