Test python 2.7, 3.5, and 3.6.
Testing older 3 versions looks like it will require more conda-forge work to overcome errors like:

UnsatisfiableError: The following specifications were found to be in conflict:
  - notebook -> ipykernel -> ipython[version='>=4.0'] -> pickleshare -> python=3.5 -> tk=8.6
  - notebook -> ipykernel -> ipython[version='>=4.0'] -> pickleshare -> python=3.5 -> xz[version='>=5.2.3,<6.0a0']
  - python=3.3