Handle updating dependencies without a semver range prefix (#10393)
* Handle updating dependencies without a semver range specifier

When updating a dependency that does not have a semver range prefix (^, ~, etc.), and not giving a prefix for the update so it should take any prefix from the existing version, we were running into problems with using the undefined value of the existing version.

In other words, when trying to update a dependency with version requirement 1.4.0 (note there is no semver range prefix - we just want an exact version) with arguments such as ‘update mypackage latest’, we would end up calculating a desired version of undefinedlatest, since the semver range prefix ended up being undefined from our regex matches against 1.4.0.

This change handles the case where matching for a semver range prefix returns an undefined prefix.

As an example, change the version requirement of @lumino/widgets in packages/application/package.json to 1.0.0 (note there is no semver range prefix). Then run:

jlpm run update:dependency '@lumino/widgets' latest --dry-run

Note there is an error like:

VersionNotFoundError: Version `undefinedlatest` for package `@lumino/widgets` could not be found


Now apply this change, and you’ll notice the dependency now updates, and correctly stays pinned to a single version:

jupyterlab/packages/application/package.json
@lumino/widgets 1.0.0 -> 1.23.0

* Lint

Co-authored-by: Jeremy Tuloup <jeremy.tuloup@gmail.com>