Fix flaky test due to strict mode violation.
```
Error: locator.waitFor: Error: strict mode violation: getByText('after sleep') resolved to 2 elements:
    1) <span class="ͼ12">'after sleep'</span> aka getByText('\'after sleep\'')
    2) <pre>before sleep↵after sleep↵</pre> aka getByText('before sleep after sleep')

Call log:
  - waiting for getByText('after sleep') to be visible

  136 |     await page.keyboard.press('x');
  137 |
> 138 |     await page.getByText('after sleep').waitFor();
      |                                         ^
  139 |
  140 |     // Press enter five times (should submit and then do nothing)
  141 |     for (let j = 0; j < 5; j++) {
    at /home/runner/work/jupyterlab/jupyterlab/galata/test/jupyterlab/outputarea-stdin.test.ts:138:41
```