Fix flaky subshell test (#18492)
## References

In https://github.com/jupyterlab/jupyterlab/pull/18486 we saw a flaky
subshell test
[fail](https://github.com/jupyterlab/jupyterlab/actions/runs/21924358895/job/63312864602?pr=18486)
the `Should support opening subshell in separate code console` test. One
failure more is due to incorrect use of `Locator.innerText()` for
assertions. This can be verified by watching the recording of the test -
the expected text is indeed there

```
Error: expect(received).toEqual(expected) // deep equality

Expected: "subshell list: ['512e4299-8e4c-466b-8c5f-d6684ca769cf']"
Received: undefined

  161 |       const subshellId = text2[0].split(':')[1].trim();
  162 |       expect(subshellId).not.toEqual('None');
> 163 |       expect(text2[5]).toEqual(`subshell list: ['${subshellId}']`);
      |                        ^
  164 |
  165 |       // Rerun %subshell in notebook now that subshell exists.
  166 |       await notebook
    at /home/runner/work/jupyterlab/jupyterlab/galata/test/jupyterlab/kernel.test.ts:163:24
```


[subshell.webm](https://github.com/user-attachments/assets/d714c01d-c8ff-40c1-ac7e-f075df431a80)


## Code changes

Playwright documentation of  `Locator.innerText()` suggests:

> NOTE If you need to assert text on the page, prefer
expect(locator).toHaveText(expected[, options]) with useInnerText option
to avoid flakiness. See assertions guide for more details.

However, this does not work if we want to assert that text in specific
line has a given value, so instead I am using the `expect().toPass()`
pattern to retry the relevant fragment.

Also, replaced `output1`, `output2` and `output3` (which was the same as
`output1`) with more descriptive `notebookOutput` and `consoleOutput`
for readability.

## User-facing changes

None

## Backwards-incompatible changes

None