Upgrade to Typescript 5.9 (#18402)
* Bump ts to 5.6.3

* Update to Typescript 5.6

* dedup yarn.lock

* Remove unnecessary typings

* Choose versions of @yarnpkg/core and @yarnpkg/libzip that are compatible with Typescript 5.6

These versions avoid the error '@yarnpkg/core/lib/miscUtils.d.ts(55,65): error TS2315: Type 'Buffer' is not generic.' and similar errors for @yarnpkg/libzip

* deduplicate

* Update to Typescript 5.9

* Fix typescript error

* Remove skipLibCheck in galata

The skipLibCheck was to work around some errors with the LinkedMap from vscode-jsonrpc that are discussed at https://github.com/microsoft/vscode-languageserver-node/pull/1644. I think the next major version of the package fixes the issue, as discussed on that PR. Unfortunately, they haven't made a release, so we'd need to update to a prerelease to get the fix.

However, even better: Claude suggested one fix is to remove the tsconfig lib "esnext" entry for Galata, which then will not pull in the problematic typing. It seems that Galata does not need that typing, so this fix seems to work.